language: ruby
rvm:
  - "1.9.3"
#before_install:
#  - command1
#  - command2
before_script:
  - "ruby -v"
  - "gem list"
  - "python -V"
script:
  - "uname -a"
  - "cat /etc/debian_version"
  - "cat /etc/lsb-release"
  - "cat /etc/redhat-release"
  - "cat /etc/fedora-release"
  - "cat /etc/SuSE-release"
notifications:
  email:
    - naya@val.co.jp
  on_success: always # default: change
  on_failure: always
