language: ruby
rvm:
  - "1.9.3"
before_install:
  - wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
  - sudo python get-pip.py
before_script:
  - "ruby -v"
  - "gem list"
  - "python -V"
  - "sudo pip help"
script:
  - "uname -a"
#  - "cat /etc/debian_version"
#  - "cat /etc/lsb-release"
#  - "cat /etc/redhat-release"
#  - "cat /etc/fedora-release"
#  - "cat /etc/SuSE-release"
notifications:
  email:
    - naya@val.co.jp
  on_success: always # default: change
  on_failure: always
